df.alltags.sub <- readRDS("./dfAlltagsSub.rds")

# The dplyr package allows you to summarize data by group, manipulate variables, 
# or create new variables based on your data

df.alltags.sub <- df.alltags.sub %>%
  mutate(ts = as_datetime(ts, tz = "UTC"), # convert ts to POSIXct format
         year = year(ts), # extract year from ts
         doy = yday(ts)) %>% # extract numeric day of year from ts
  filter(!is.na(recvLat))
head(df.alltags.sub)

# Summarizing based on group, in this case motusTagID
tagSummary <- df.alltags.sub %>% group_by(motusTagID) %>% 
  summarize(nDet = n(), # get number of detections
            nRecv = length(unique(recvDeployName)), # number of receivers
            tsMin = min(ts), # first detection
            tsMax = max(ts), # last detection
            totDay = length(unique(doy))) # total number of days detected

head(tagSummary)

# or you can plot by multiple groups
# same as above by grouping by motusTagID AND recvDeployName
tagRecvSummary <- df.alltags.sub %>% group_by(motusTagID, recvDeployName) %>% 
  summarize(nDet = n(), 
            nRecv = length(unique(recvDeployName)), 
            tsMin = min(ts), 
            tsMax = max(ts), 
            totDay = length(unique(doy)))

head(tagRecvSummary)

## plotting
# often when making summary plots it's useful to round your detection data
# to the nearest hour or day for faster processing:
df.alltags.sub.2 <- mutate(df.alltags.sub, hour = as.POSIXct(round(ts, "hour"))) %>% 
  select(motusTagID, port, tagDeployStart, tagDeployLat, tagDeployLon, recvLat, 
         recvLon, recvDeployName, antBearing, speciesEN, year, doy, hour) %>% distinct()

# now we can plot hourly detections of 2016 tasg, coloured by species
p <- ggplot(data = filter(df.alltags.sub.2, year(tagDeployStart) == 2016), 
            aes(hour, as.factor(motusTagID), col = speciesEN))
p + geom_point() + ylab("MotusTagID") + xlab("Time (rounded to hour)") + 
  scale_colour_discrete(name = "Species") + theme_bw()

# or we can see how tags move latitudinally
df.alltags.sub.2 <- arrange(df.alltags.sub.2, hour)

p <- ggplot(data = filter(df.alltags.sub.2, year(tagDeployStart) == 2016), 
            aes(hour, recvLat, col = as.factor(motusTagID), group = as.factor(motusTagID)))
p + geom_point() + geom_path() + theme_bw() + xlab("Time (rounded to hour)") + 
  ylab("Receiver latitude") + scale_colour_discrete(name = "MotusTagID")

# We can also look at signal variation to assess behaviour on a finer scale
p <- ggplot(filter(df.alltags.sub, motusTagID == 22897, 
                   recvDeployName == "Niapiskau"), aes(ts, sig))
p + theme_bw() + geom_point() + xlab("Time") + ylab("Signal strength") + 
  facet_grid(recvDeployName ~ .)

# and we can use functions from the motus R package to add sunrise/sunset times
df.alltags.sun <- sunRiseSet(df.alltags.sub, lat = "recvLat", 
                             lon = "recvLon")

p <- ggplot(filter(df.alltags.sun, motusTagID == 22897 & 
                     ts > ymd("2016-10-12") & ts < ymd("2016-10-15") & 
                     recvDeployName == "Niapiskau"), aes(ts, sig))

p + theme_bw() + geom_point() + xlab("Time of year") + ylab("Signal strength") + 
  geom_vline(xintercept = filter(df.alltags.sun, recvDeployName == "Niapiskau")$sunrise,col = "orange") + 
  geom_vline(xintercept = filter(df.alltags.sun, recvDeployName == "Niapiskau")$sunset, col = "blue")

# We can also zoom in on detections even more to see fly bys for example
p <- ggplot(filter(df.alltags.sub, motusTagID == 16039, 
                   ts > ymd("2015-09-14"), ts < ymd("2015-10-01")), 
            aes(ts, sig, col = as.factor(antBearing)))
p + theme_bw() + geom_point() + xlab("Time of day") + 
  ylab("Signal strength") + scale_color_discrete(name = "Antenna bearing") + 
  facet_grid(recvDeployName ~ .)

# Maps
# a simple outline map can be generated by first loading the base maps
na.lakes <- map_data(map = "lakes")
na.lakes <- na.lakes %>% mutate(long = long - 360)

# Include all of the Americas to begin
na.map <- map_data(map = "world2")
na.map <- na.map %>% filter(region %in% c("Canada", 
                                          "USA")) %>% mutate(long = long - 360)

# We then set the x and y-axis limits, in this case based on location of receivers with detections
# set limits to map based on locations of
# detections, ensuring they include the deployment
# locations
xmin <- min(df.tmp$recvLon, na.rm = TRUE) - 2
xmax <- max(df.tmp$recvLon, na.rm = TRUE) + 2
ymin <- min(df.tmp$recvLat, na.rm = TRUE) - 1
ymax <- max(df.tmp$recvLat, na.rm = TRUE) + 1

# now let's get our database, and only look at specified tags:
# just use the tags that we have examined carefully and filtered (in the previous chapter)
df.tmp <- filter(df.alltags.sub, 
                 motusTagID %in% c(16011, 16035, 16036, 16037, 16038, 16039))
df.tmp <- arrange(df.tmp, ts.h) # arange by hour
df.tmp <- as.data.frame(df.tmp)

